ComputerGarage/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerGarage.Data;
using ComputerGarage.Models;
using ComputerGarage.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.Web;

namespace ComputerGarage.Controllers
{
    public class AdminController : BaseController
    {
        public AdminController(ComputerGarageDbContext context, UserManager<ComputerGarageUser> userManager)
            : base(context, userManager) { }

        public IActionResult Open()
        {
            return View("AdminMainPage");
        }

        #region Administruoti darbuotojų paskyras
        public IActionResult OpenWorkersPage()
        {

            return View("AdminWorkersPage");
        }

        #endregion

        #region Administruoti užsakovų paskyras
        public IActionResult openCustomersPage()
        {
            return View("AdminCustomersPage");
        }
        #endregion

        #region Šalinti užsakovą

        public IActionResult openDeleteCustomer()
        {
            return View("DeleteCustomerPage");
        }

        public async Task<IActionResult> customerUserName(string username)
        {
            //findCustomer()
            var user = context.Users.Include(x => x.UserProfile).Where(x => x.Email == username).ToList();//suranda user su profile
            bool isCustomer = false;
            if(user.Count > 0)
            {
                isCustomer = await userManager.IsInRoleAsync(user[0], Roles.Customer);
            }

            if(user.Count > 0 && isCustomer)
            {
                //deleteCustomer()
                var delete = context.Customers.Find(user[0].UserProfile.Id);//istrins customers row
                context.Remove(delete);
                context.SaveChanges();

                //openCustomersPage()
                base.AddSuccess("Užsakovas sėkmingai pašalintas");
                return RedirectToAction("OpenCustomersPage");
            }

            //openDeleteCustomer()
            return RedirectToAction("openDeleteCustomer");
        }


        #endregion

        #region Redaguoti darbuotoją
        public IActionResult OpenSearch()
        {
            return View("FindUserPage");
        }

        private static int id = -1;//editinamo userio id
        public async Task<IActionResult> enterName(string username)
        {
            //find()
            var user = context.Users.Include(x => x.UserProfile).Where(x => x.Email == username).ToList();//suranda user su profile
            bool isEmployee = false;

            if (user.Count > 0)
            {
                isEmployee = await userManager.IsInRoleAsync(user[0], Roles.Employee);
            }

            if (user.Count > 0 && isEmployee)
            {
                //openUsersEditPage()
                id = user[0].Id;
                return View("AdminEditWorkerPage", user[0]);
            }

            base.AddError("Vartotojas nebuvo rastas");
            return RedirectToAction("OpenSearch");
        }

        public IActionResult editData(string name, string surename)
        {
            
            //checkData
            if(name.Length > 3 && surename.Length > 3)
            {
                //saveWorkerData()
                var user = context.Customers.Where(x => x.Id == id).ToList();//Customer table
                if(user.Count > 0)
                {
                    user[0].FirstName = name;
                    user[0].LastName = surename;

                    context.Customers.Update(user[0]);//atnaujiname customer table
                    context.SaveChanges();
                }
                //openWorkersPage()
                return View("AdminWorkersPage");
            }

            return RedirectToAction("OpenSearch");
        }
        #endregion

        #region Šalinti darbuotoją
        public IActionResult OpenDeleteWorker()
        {
            return View("DeleteUserPage");
        }

        public async Task<IActionResult> workerUserName(string username)
        {
            //find()
            var user = context.Users.Include(x => x.UserProfile).Where(x => x.Email == username).ToList();//suranda user su profile
            bool isEmployee = false;

            if(user.Count > 0)
            {
                isEmployee = await userManager.IsInRoleAsync(user[0], Roles.Employee);
            }

            if(user.Count > 0)
            {
                //deleteUser()
                var delete = context.Customers.Find(user[0].UserProfile.Id);//istrins employee row
                context.Remove(delete);
                context.SaveChanges();

                //openUsersEditPage()
                base.AddSuccess("Darbuotojas sėkmingai pašalintas");
                return RedirectToAction("OpenWorkersPage");
            }

            return View("DeleteUserPage");
        }
        #endregion

        #region Kurti darbuotoją
        public IActionResult OpenCreate()
        {
            return View("AdminCreateWorkerPage");
        }

        [HttpPost]
        public async Task<IActionResult> createWorker(string name, string surename, string email, string password, string password2)
        {
            //checkData()
            if (password != password2)
            {
                base.AddError("Įvesti slaptažodžiai nesutampa");
                return RedirectToAction("OpenCreate");
            }
            if(name == "" || surename == "" || email == "" || password == "" || password2 == "")
            {
                base.AddError("Palikote neįvestų laukų!");
                return RedirectToAction("OpenCreate");
            }

            //saveWorker()
            var newUser = new ComputerGarageUser()
            {
                Email = email,
                UserName = email,
                UserProfile = new Customer()
                {
                    FirstName = name,
                    LastName = surename,
                    Email = email
                }
            };
           // base.AddSuccess(newUser.UserProfile.FirstName);
            var result = await userManager.CreateAsync(newUser, password);
            var roleResult = await userManager.AddToRoleAsync(newUser, Roles.Employee);

            base.AddSuccess("Darbuotojas sėkmingai sukurtas");
            //openAdminPage()
            return RedirectToAction("OpenWorkersPage");
        }


        #endregion
    }
}

ComputerGarage/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerGarage.Data;
using ComputerGarage.Models;
using ComputerGarage.Security;
using ComputerGarage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ComputerGarage.Controllers
{
    [Authorize(Roles = Roles.Customer + "," + Roles.Employee)]
    public class ClientController : BaseController
    {
        public ClientController(ComputerGarageDbContext context, UserManager<ComputerGarageUser> userManager)
            : base(context, userManager) { }

        #region RepairRequest
        public IActionResult OpenRepairRequestNewPage()
        {
            var model = new RepairRequestCreateViewModel();
            return View("RepairRequestNewPage", model);
        }

        [HttpPost]
        public async Task<IActionResult> EnterRequestData(RepairRequestCreateViewModel model)
        {
            if (ValidateRepairRequestData(ModelState))
            {
                var repairRequest = new RepairRequest()
                {
                    State = Models.States.RequestState.Submitted,
                    DateCreated = DateTime.Now,
                    Submitter = await userManager.FindByNameAsync(User.Identity.Name),
                    MalfunctionDescription = model.MalfunctionDescription,
                    ComputerName = model.ComputerName
                };
                context.Add(repairRequest);

                //create()
                context.SaveChanges();

                //show success message
                AddSuccess("Sekmingai issaugota");
                return RedirectToAction("OpenRepairRequestListPage");
            }
            else
            {
                //show error message
                return View("RepairRequestNewPage", model);
            }
        }
        
        public async Task<IActionResult> OpenRepairRequestListPage()
        {
            //selectAllRequests
            var repairRequests = context.Set<RepairRequest>().AsQueryable();

            var user = await userManager.FindByNameAsync(User.Identity.Name);
            if (await userManager.IsInRoleAsync(user, Roles.Customer))
            {
                repairRequests = repairRequests.Where(x => x.Submitter.Id == user.Id);
            }

            //showList()
            return View("RepairRequestListPage", repairRequests.OrderByDescending(x => x.DateCreated));
        }
        #endregion

        #region RepairOrder
        public async Task<IActionResult> OpenOrderListPage()
        {
            //selectAllOrders()
            var orders = context.Set<RepairOrder>().AsQueryable();

            var user = await userManager.FindByNameAsync(User.Identity.Name);
            if (await userManager.IsInRoleAsync(user, Roles.Customer))
            {
                orders = orders.Where(x => x.Request.Submitter.Id == user.Id);
            }

            return View("RepairOrderListPage", orders.OrderByDescending(x => x.DateCreated));
        }

        public IActionResult GetOrderPage(int id)
        {
            //find(ID=)
            var repairOrder = context.Set<RepairOrder>().Find(id);

            //showOrderPage()
            return View("RepairOrderDetailsPage", repairOrder);
        }

        [HttpPost]
        public IActionResult ConfirmOrder(int id)
        {
            var repairOrder = context.Set<RepairOrder>().Find(id);

            //update()
            repairOrder.State = Models.States.RepairOrderState.Confirmed;
            context.SaveChanges();

            //order confirmed
            base.AddSuccess("Užsakymas sėkmingai patvirtinas");

            return RedirectToAction("OpenOrderListPage");
        }
        #endregion

        private bool ValidateRepairRequestData(ModelStateDictionary modelState)
        {
            return modelState.IsValid;
        }
    }
}

ComputerGarage/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerGarage.Data;
using ComputerGarage.Models;
using ComputerGarage.Security;
using ComputerGarage.Services;
using ComputerGarage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ComputerGarage.Controllers
{
    [Authorize(Roles = Roles.Employee)]
    public class EmailController : BaseController
    {
        private readonly IEmailService emailService;

        public EmailController(ComputerGarageDbContext context, UserManager<ComputerGarageUser> userManager, IEmailService emailService)
            : base(context, userManager)
        {
            this.emailService = emailService;
        }

        public IActionResult OpenEmailPage() => View("SendEmailMessagePage");

        [HttpPost]
        public IActionResult Send(string emailTo, string text)
        {
            //send()
            bool result = emailService.SendEmail(emailTo, text);
            if (result)
            {
                base.AddSuccess("Laiskas sekmingai issiustas");
            }
            else
            {
                base.AddSuccess("Laisko nepaviko issiusti");
            }
            return RedirectToAction("OpenEmailPage");
        }
    }
}

ComputerGarage/Controllers/RepairController.cs
using ComputerGarage.Data;
using ComputerGarage.Models;
using ComputerGarage.Models.States;
using ComputerGarage.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerGarage.Controllers
{
    [Authorize(Roles = Roles.Employee)]
    public class RepairController : BaseController
    {
        public RepairController(ComputerGarageDbContext context,
            UserManager<ComputerGarageUser> userManager) : base(context, userManager)
        { }
        
        public IActionResult GetEquipmentPage()
        {
            var repairOrders = context.Set<RepairOrder>()
                .Where(x => x.State == RepairOrderState.Confirmed)
                .Select(x => new SelectListItem
                {
                    Text = x.Request.ComputerName + " " + x.DateCreated.ToShortDateString(),
                    Value = x.Id.ToString()
                }).ToList();

            return View("RegisterEquipmentPage", repairOrders);
        }
        
        [HttpPost]
        public IActionResult RegisterReceivedEquipment(int id)
        {
            var repairOrder = context.Set<RepairOrder>().Find(id);
            //changeOrderState()
            repairOrder.State = RepairOrderState.DeliveredToGarage;
            context.SaveChanges();

            //success message
            base.AddSuccess("Įranga užregistruota");
            return RedirectToAction("GetEquipmentPage");
        }

        public IActionResult OpenRepairPage()
        {
            //open()
            return View("AdminRepairPage", context.Set<RepairRequest>());
        }
    }
}

ComputerGarage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComputerGarage</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @*@{
        var authResult = await AuthorizationService.AuthorizeAsync(User, null, ComputerGarage.Security.Policies.Employee);
        var adminResult = await AuthorizationService.AuthorizeAsync(User, null, ComputerGarage.Security.Policies.Administrator);
    }*@
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ComputerGarage</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li asp-authorize="true" asp-roles="Customer"><a asp-area="" asp-controller="Client" asp-action="OpenRepairRequestListPage">Remonto užklausos</a></li>
                    <li asp-authorize="true" asp-roles="Customer"><a asp-area="" asp-controller="Client" asp-action="OpenOrderListPage">Remonto užsakymai</a></li>
                    <li asp-authorize="true" asp-roles="Employee"><a asp-area="" asp-controller="Repair" asp-action="GetEquipmentPage">Registruoti gautą įrangą</a></li>
                    <li asp-authorize="true" asp-roles="Administrator"><a asp-area="" asp-controller="Admin" asp-action="Open">Administratoriaus langas</a></li>
                    <li asp-authorize="true" asp-roles="Customer"><a asp-area="" asp-controller="EditProfile" asp-action="OpenEditProfilePage">Redaguoti profilį</a></li>
                    <li asp-authorize="true" asp-roles="Employee"><a asp-area="" asp-controller="Email" asp-action="OpenEmailPage">Siųsti el. laišką</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li asp-authorize="false"><a asp-area="" asp-controller="Home" asp-action="Login">Prisijungti</a></li>
                    <li asp-authorize="false"><a asp-area="" asp-controller="Register" asp-action="OpenRegisterPage">Registruotis</a></li>
                    <li asp-authorize="true"><a asp-area="" asp-controller="Home" asp-action="Logout">Atsijungti</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @Html.ErrorMessage()
        @Html.SuccessMessage()

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ComputerGarage</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>